#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "prometheus"
name = "Prometheus"
description.en = "Monitoring system and time series database"
description.fr = "Supervision chronologique de systèmes et services"

version = "3.11.2~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io"
demo = "https://demo.do.prometheus.io"
admindoc = "https://prometheus.io/docs"
code = "https://github.com/prometheus/prometheus"
cpe = "cpe:2.3:a:prometheus:prometheus"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["i386", "amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prometheus"

[resources]
    [resources.sources]
    [resources.sources.main]
    i386.url = "https://github.com/prometheus/prometheus/releases/download/v3.11.2/prometheus-3.11.2.linux-386.tar.gz"
    i386.sha256 = "921d59d9a2014bb2d417a48dc54bac0f694367c16f158b8240baf6b8366f4f8b"

    amd64.url = "https://github.com/prometheus/prometheus/releases/download/v3.11.2/prometheus-3.11.2.linux-amd64.tar.gz"
    amd64.sha256 = "f643ea1ee90d109329302d27bddb1fb2e52655b1fa84e9e26f9a6f340da144a6"

    armhf.url = "https://github.com/prometheus/prometheus/releases/download/v3.11.2/prometheus-3.11.2.linux-armv7.tar.gz"
    armhf.sha256 = "0cc413eb6cac911b8803c1bf8539373eab1478097313a7fa4e82bb22a0a17b0d"

    arm64.url = "https://github.com/prometheus/prometheus/releases/download/v3.11.2/prometheus-3.11.2.linux-arm64.tar.gz"
    arm64.sha256 = "4e40f115655a3021744137f49287846bc5a59e02835565748ff66b23e776a73d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*linux-386.tar.gz"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.ports]
    main.default = 9090
