#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "prometheus"
name = "Prometheus"
description.en = "Monitoring system and time series database"
description.fr = "Supervision chronologique de systèmes et services"

version = "3.14.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io"
demo = "https://demo.do.prometheus.io"
admindoc = "https://prometheus.io/docs"
code = "https://github.com/prometheus/prometheus"
cpe = "cpe:2.3:a:prometheus:prometheus"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["i386", "amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prometheus"

[resources]
    [resources.sources]
    [resources.sources.main]
    i386.url = "https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-386.tar.gz"
    i386.sha256 = "9e0bcc54d4c0f574d7d1c5168014b565bdc5dbbc118f33cf5cc4630f39e1664f"

    amd64.url = "https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-amd64.tar.gz"
    amd64.sha256 = "f665c6da19eb7ba399c915d30c7d9793c9b417bf8a749b504bc470678631478d"

    armhf.url = "https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-armv7.tar.gz"
    armhf.sha256 = "60f9251e84b0f5f9cb2c0d29d92dd0fd7c0dd98c946d781915c3c27e592c1d3a"

    arm64.url = "https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-arm64.tar.gz"
    arm64.sha256 = "077f3781ab7245dc04c9a3c9b78ba120fc8e41aa0dc97489b0af67247e50ba83"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*linux-386.tar.gz"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.ports]
    main.default = 9090
