#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "prometheus"
name = "Prometheus"
description.en = "Monitoring system and time series database"
description.fr = "Supervision chronologique de systèmes et services"

version = "3.10.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io"
demo = "https://demo.do.prometheus.io"
admindoc = "https://prometheus.io/docs"
code = "https://github.com/prometheus/prometheus"
cpe = "cpe:2.3:a:prometheus:prometheus"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["i386", "amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prometheus"

[resources]
    [resources.sources]
    [resources.sources.main]
    i386.url = "https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-386.tar.gz"
    i386.sha256 = "bb6713329bce2658798ce7f358c709978c01063c48ec09603291be7065ce6b22"

    amd64.url = "https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-amd64.tar.gz"
    amd64.sha256 = "41c50d97bb6a181623fc89d3fe61d0cc68ee69cc93da9091b8bba005f9690122"

    armhf.url = "https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-armv7.tar.gz"
    armhf.sha256 = "e5c60ca4d1f0f329820e10c87b94a8587bab35072020ffb98faaf4dba0097e73"

    arm64.url = "https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-arm64.tar.gz"
    arm64.sha256 = "f6fc81c7955b6e1ddd532c62b55896f7e7a61d997a3817ac3534114f2dd33ab1"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*linux-386.tar.gz"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.ports]
    main.default = 9090
