#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=3

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

log_path="/var/log/$app"
mkdir -p "$log_path"
touch "$log_path/$app.log"
chmod 750 "$log_path"
chmod -R o-rwx "$log_path"
chown -R $app:$app "$log_path"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring the app..." --weight=2

ynh_replace_string --match_string="localhost:9090" --replace_string="localhost:$port" --target_file="$install_dir/prometheus.yml"
echo "    metrics_path: $path/metrics" >> "$install_dir/prometheus.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --description="Prometheus daemon" --log="systemd"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="systemd" --line_match="Started Prometheus daemon" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
