#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

log_path="/var/log/$app"
mkdir -p "$log_path"
touch "$log_path/$app.log"
chmod 750 "$log_path"
chmod -R o-rwx "$log_path"
chown -R $app:$app "$log_path"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Configuring the app..."

ynh_replace --match="localhost:9090" --replace="localhost:$port" --file="$install_dir/prometheus.yml"
echo "    metrics_path: $path/metrics" >> "$install_dir/prometheus.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Prometheus daemon" --log="systemd"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Started Prometheus daemon" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
