#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before 3.13.1~ynh1; then
    ynh_permission_has_user --permission=api --user=visitors && ynh_permission_update --permission "api" --remove="visitors"
    ynh_print_warn "Visitors permission to the API has been revoked, cf. pre-upgrade message and app's documentation."
fi

[ ! -f "$install_dir/web.yml" ] && ynh_config_add --template="web.yml" --destination="$install_dir/web.yml"
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"  --keep="prometheus.yml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Prometheus daemon" --log="systemd"

ynh_config_add_logrotate
ynh_config_add_logrotate "$install_dir/.data/logs"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Started $app" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
